<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <AssemblyName>Glance</AssemblyName>
    <ApplicationIcon>assets\glance.ico</ApplicationIcon>
    <Version>1.6.0</Version>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests/**;android/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="assets\glance.ico" />
  </ItemGroup>
</Project>
